---

# Find an IP address on the memcached network 
# (This magic came from http://docs.ansible.com/ansible/latest/playbooks_filters_ipaddr.html)
- set_fact:
    memcached_ip: []
- set_fact:
    memcached_ip: "{{ memcached_ip + [ item ] }}"
  when: item | ipaddr(memcached_network_cidr)
  with_items: "{{ ansible_all_ipv4_addresses }}"

- name: Make list of listen ips, including localhost. This will be used in memcached.conf template -l option
  set_fact:
    memcached_listen_ips: "{{ memcached_ip + [ 'localhost' ] }}"

- debug:
    var: memcached_network_cidr
- debug:
    var: memcached_ip
- debug:
    var: memcached_listen_ips

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define memcached_user.
  set_fact:
    memcached_user: "{{ __memcached_user }}"
  when: memcached_user is not defined

- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400
  when: ansible_os_family == 'Debian'

- name: Install Memcached.
  package: name=memcached state=installed
  register: memcached_install

- name: Install Memcached Tools (allows monitoring memcached with memcstat).
  package: name=libmemcached-tools state=installed

- name: Copy Memcached configuration.
  template:
    src: memcached-{{ ansible_os_family }}.conf.j2
    dest: "{{ memcached_config_file }}"
    owner: root
    group: root
    mode: 0644
  notify: restart memcached

- name: Ensure Memcached is started and set to run on startup.
  service: name=memcached state=started enabled=yes
